{
  "openapi": "3.0.0",
  "info": {
    "title": "Оплата баллами бонусов merged",
    "description": "Позволяет пользователям просматривать и использовать свои награды.",
    "version": "2.0"
  },
  "servers": [
    {
      "url": "https://api.bankingapi.ru/api/rb/rewardsPay/hackathon/v1",
      "description": "Адрес API в песочнице хакатона"
    }
  ],
  "paths": {
    "/cards/accounts/external/{externalAccountID}/rewards/balance": {
      "summary": "Операции с Account ID.",
      "description": "Операции с Account ID.",
      "get": {
        "tags": [
          "Оплата баллами бонусов"
        ],
        "summary": "Получить текущий баланс наград для указанного аккаунта и атрибутов программы, настроенных для конкретного партнера",
        "description": "Получить текущий баланс наград для данного аккаунта.",
        "operationId": "getRewardsBalance",
        "deprecated": false
      }
    },
    "/cards/accounts/external/{externalAccountID}/rewards/redemption": {
      "summary": "Operations by Account ID.",
      "description": "Operations by Account ID.",
      "post": {
        "tags": [
          "Оплата баллами бонусов"
        ],
        "summary": "Выполните выписку по кредиту для данного аккаунта и соответствующих атрибутов программы.",
        "description": "Списывает вознаграждение с данного счета и публикует выписку по кредиту. Возвращает идентификатор погашения для отслеживания.",
        "operationId": "processRedemption",
        "deprecated": false
      }
    },
    "/leads": {
      "get": {
        "tags": [
          "LeadStatus"
        ],
        "summary": "Получить информацию о лидах",
        "description": "Метод получения информации о лидах (заявках на создание юридических лиц)",
        "operationId": "getLeadStatusUsingGet",
        "deprecated": false
      }
    },
    "/leads_impersonal": {
      "post": {
        "tags": [
          "AddLead"
        ],
        "summary": "Добавить лиды",
        "description": "Добавляет лидов (заявки на создание юридических лиц) без персональных данных для дальнейшей обработки (звонков, контактов) с целью привлечения клиентов. Запрос может быть выполнен частично, то есть часть лидов из списка будет добавлена, а часть нет.",
        "operationId": "createLeadsUsingPost",
        "deprecated": false
      }
    },
    "/check_leads": {
      "post": {
        "tags": [
          "CheckLead"
        ],
        "summary": "Проверяет лидов",
        "description": "Метод проверки лидов",
        "operationId": "checkLeadsUsingPost",
        "deprecated": false
      }
    },
    "/products": {
      "post": {
        "description": "Получение списка продуктов, доступных для оплаты сотового платежа",
        "tags": [
          "client-product-controller"
        ],
        "summary": "Получение списка продуктов, доступных для оплаты сотового платежа",
        "operationId": "getClientProducts"
      }
    },
    "/products/{productId}": {
      "get": {
        "tags": [
          "Products"
        ],
        "summary": "Детальная информация о продукте по его идентификатору",
        "description": "Конечная точка позволяет получить детальную информацию о финансовом продукте кредитной организации по его идентификатору.",
        "operationId": "getProductsProductId",
        "security": [
          {
            "TPPOAuth2Security": [
              "opendata"
            ]
          }
        ]
      }
    },
    "/customer-leads": {
      "post": {
        "tags": [
          "Customer lead"
        ],
        "summary": "Создать ресурс лидогенерации",
        "description": "Конечная точка позволяет передать информацию о лидогенерации от Стороннего поставщика к Поставщику услуг",
        "operationId": "CreateCustomerLeads",
        "security": [
          {
            "TPPOffersOAuth2Security": [
              "offers"
            ]
          }
        ]
      }
    },
    "/customer-leads/{customerLeadId}": {
      "get": {
        "tags": [
          "Customer lead"
        ],
        "summary": "Детали лидогенерации",
        "description": "Конечная точка позволяет получить информацию о статусе и деталях лидогенерации по идентификатору",
        "operationId": "GetCustomerLeadsCustomerLeadId",
        "security": [
          {
            "PSUOffersOAuth2Security": [
              "offers"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "DeleteCustomerLeadsCustomerLeadId",
        "tags": [
          "Customer lead"
        ],
        "summary": "Удаление лидогенерации",
        "description": "Конечная точка позволяет удалять ресурс лидогенерации",
        "security": [
          {
            "TPPOffersOAuth2Security": [
              "offers"
            ]
          }
        ]
      }
    },
    "/product-offers": {
      "post": {
        "tags": [
          "Product offers"
        ],
        "summary": "Создать ресурс Предложения по продукту",
        "description": "Конечная точка позволяет инициировать получение Предложения по продукту для лида от Стороннего поставщика к Поставщику услуг",
        "operationId": "CreateProductOffers",
        "security": [
          {
            "PSUOffersOAuth2Security": [
              "offers"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Product offers"
        ],
        "summary": "Список всех Предложений по продукту для лида",
        "description": "Конечная точка позволяет получить информацию о списке всех Предложений по продукту для определенной лидогенерации",
        "operationId": "GetProductOffers",
        "security": [
          {
            "PSUOffersOAuth2Security": [
              "offers"
            ]
          }
        ]
      }
    },
    "/product-offers/{offerId}": {
      "get": {
        "tags": [
          "Product offers"
        ],
        "summary": "Детали Предложения по продукту для лида",
        "description": "Конечная точка позволяет получить детальную информацию о предложении по продукту по идентификатору",
        "operationId": "GetProductOffersOfferId",
        "security": [
          {
            "PSUOffersOAuth2Security": [
              "offers"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "DeleteProductOffersOfferId",
        "tags": [
          "Product offers"
        ],
        "summary": "Удаление Предложения по продукту",
        "description": "Конечная точка позволяет удалять ресурс Предложения по продукту",
        "security": [
          {
            "PSUOffersOAuth2Security": [
              "offers"
            ]
          }
        ]
      }
    },
    "/product-offer-consents": {
      "post": {
        "tags": [
          "Product consent"
        ],
        "summary": "Создать ресурс Согласия на предложение по продукту",
        "description": "Конечная точка позволяет создать ресурс Согласия на предложение по продукту с целью дальнейшего инициирования его получение Пользователем",
        "operationId": "CreateProducOfferConsent",
        "security": [
          {
            "PSUOffersOAuth2Security": [
              "offers"
            ]
          }
        ]
      }
    },
    "/product-offer-consents/{consentId}": {
      "get": {
        "tags": [
          "Product consent"
        ],
        "summary": "Детали Согласия на предложение по продукту",
        "description": "Конечная точка позволяет получить детальную информацию о согласии на предложение по продукту",
        "operationId": "GetProductOfferConsentsConsentId",
        "security": [
          {
            "PSUOffersOAuth2Security": [
              "offers"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "DeleteProductOfferConsentsConsentId",
        "tags": [
          "Product consent"
        ],
        "summary": "Удаление Согласия на предложение по продукту",
        "description": "Конечная точка позволяет удалять ресурс Согласия на предложение по продукту",
        "security": [
          {
            "PSUOffersOAuth2Security": [
              "offers"
            ]
          }
        ]
      }
    },
    "/product-application": {
      "post": {
        "tags": [
          "Product application"
        ],
        "summary": "Создать ресурс Заявления по продукту",
        "description": "Конечная точка позволяет инициировать получение продукта Пользователем, на который он авторизовал предложение, с помощью создание ресурса продукта на стороне Поставщика услуг.",
        "operationId": "CreateProductApplication",
        "security": [
          {
            "PSUProductsOAuth2Security": [
              "products"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Product application"
        ],
        "summary": "Список завлений по продукту и статус",
        "description": "Конечная точка позволяет получить информацию о статусе всех заявлений по продукту Пользователя",
        "operationId": "GetProductApplication",
        "security": [
          {
            "PSUProductsOAuth2Security": [
              "products"
            ]
          }
        ]
      }
    },
    "/product-application/{productApplicationId}": {
      "get": {
        "tags": [
          "Product application"
        ],
        "summary": "Детали Заявления по продукту",
        "description": "Конечная точка позволяет получить детальную информацию о заявлении по продукту Пользователя.",
        "operationId": "GetProductApplicationProductApplicationId",
        "security": [
          {
            "PSUProductsOAuth2Security": [
              "products"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "DeleteProductApplicationProductApplicationId",
        "tags": [
          "Product application"
        ],
        "summary": "Удаление Заявления по продукту",
        "description": "Конечная точка позволяет удалять ресурс Заявления по продукту",
        "security": [
          {
            "PSUProductsOAuth2Security": [
              "products"
            ]
          }
        ]
      }
    },
    "/applications": {
      "post": {
        "tags": [
          "partner-application-controller"
        ],
        "summary": "Сохранить данные по заявке",
        "description": "Данный метод сохраняет данные по заявке и возвращает уникальный идетификатор заявки",
        "operationId": "create"
      }
    },
    "/applications/{applicationId}": {
      "get": {
        "tags": [
          "partner-application-controller"
        ],
        "summary": "Проверить статус заявки",
        "description": "Данный метод возвращает статус заявки",
        "operationId": "check"
      },
      "patch": {
        "tags": [
          "partner-application-controller"
        ],
        "summary": "Принять предложение",
        "description": "Данный метод принимает предложение по заявке",
        "operationId": "confirm"
      }
    },
    "/credentials/{publicId}": {
      "get": {
        "security": [
          {
            "EpaAuth": []
          }
        ],
        "tags": [
          "API для работы с картами"
        ],
        "description": "Метод получения реквизитов карты",
        "operationId": "getCredentials",
        "summary": "Получение реквизитов карты"
      }
    },
    "/cvv/{publicId}": {
      "get": {
        "security": [
          {
            "EpaAuth": []
          }
        ],
        "tags": [
          "API для работы с картами"
        ],
        "description": "Метод получения CVV кода карты",
        "operationId": "getCvv",
        "summary": "Получение кода CVV карты"
      }
    },
    "/token/{publicId}": {
      "post": {
        "security": [
          {
            "EpaAuth": []
          }
        ],
        "tags": [
          "API для работы с картами"
        ],
        "description": "Операция токенизации карты",
        "operationId": "updateTokenize",
        "summary": "Токенизация карты"
      }
    },
    "/tokens/{publicId}": {
      "get": {
        "security": [
          {
            "EpaAuth": []
          }
        ],
        "tags": [
          "API для работы с картами"
        ],
        "description": "Метод получения токенов карты",
        "operationId": "getTokens",
        "summary": "Получение токенов карты"
      }
    },
    "/close/{publicId}": {
      "post": {
        "security": [
          {
            "EpaAuth": []
          }
        ],
        "tags": [
          "API для работы с картами"
        ],
        "description": "Метод закрытия карты",
        "operationId": "updateCloseCard",
        "summary": "Закрытие карты при нулевом балансе"
      }
    },
    "/pin/{publicId}": {
      "post": {
        "security": [
          {
            "EpaAuth": []
          }
        ],
        "tags": [
          "API для работы с картами"
        ],
        "description": "Метод смены PIN-кода карты",
        "operationId": "updateCardPin",
        "summary": "Установка/смена пин-кода для карты"
      }
    },
    "/status/{publicId}": {
      "put": {
        "security": [
          {
            "EpaAuth": []
          }
        ],
        "tags": [
          "API для работы с картами"
        ],
        "description": "Метод установки статуса карты",
        "operationId": "updateCardOption",
        "summary": "Установка/смена статуса карты"
      }
    },
    "/prepaid": {
      "post": {
        "security": [
          {
            "EpaAuth": []
          }
        ],
        "tags": [
          "API для работы с картами"
        ],
        "description": "Метод открытия карты",
        "operationId": "updateCreateCard",
        "summary": "Открытие карты"
      }
    },
    "/payments/{paymentId}": {
      "get": {
        "description": "Запрос детальной информации по платежу",
        "tags": [
          "mobile-payment-controller"
        ],
        "summary": "Запрос детальной информации по платежу",
        "operationId": "getPayment"
      }
    },
    "/payments/confirm": {
      "post": {
        "description": "Запрос на подтверждение оплаты номера мобильного телефона",
        "tags": [
          "mobile-payment-controller"
        ],
        "summary": "Запрос на подтверждение оплаты номера мобильного телефона",
        "operationId": "confirm"
      }
    },
    "/payments/request": {
      "post": {
        "description": "Запрос на оплату номера мобильного телефона",
        "tags": [
          "mobile-payment-controller"
        ],
        "summary": "Запрос на оплату номера мобильного телефона",
        "operationId": "request"
      }
    },
    "/payments/{paymentId}/check": {
      "get": {
        "description": "Запрос чека по платежу",
        "tags": [
          "mobile-payment-controller"
        ],
        "summary": "Запрос чека по платежу",
        "operationId": "getPaymentCheck"
      }
    },
    "/payments/start": {
      "post": {
        "description": "Запрос для старта платежа",
        "tags": [
          "mobile-payment-controller"
        ],
        "summary": "Запрос для старта платежа",
        "operationId": "startPayment"
      }
    },
    "/phones/info": {
      "post": {
        "description": "Получение параметров сотового оператора для указанного номера телефона",
        "tags": [
          "mobile-number-controller"
        ],
        "summary": "Получение параметров сотового оператора для указанного номера телефона",
        "operationId": "getMobileNumberInfo"
      }
    },
    "/catalog/operations": {
      "get": {
        "tags": [
          "Клиентское API"
        ],
        "summary": "Поиск услуг ПУ",
        "description": "Поиск услуг по фильтрам",
        "operationId": "findOperations"
      }
    },
    "/catalog/operations/{id}": {
      "get": {
        "tags": [
          "Клиентское API"
        ],
        "summary": "Получение услуги ПУ по ID",
        "description": "Получение договорной (type = CONTRACT) услуги ПУ по идентификатору",
        "operationId": "getOperation"
      }
    },
    "/catalog/operations/list": {
      "get": {
        "tags": [
          "Клиентское API"
        ],
        "summary": "Получение услуг ПУ по списку ID",
        "description": "Получение договорных (type = CONTRACT) услуг ПУ по списку идентфикаторов",
        "operationId": "findOperations_1"
      }
    },
    "/catalog/categories": {
      "get": {
        "tags": [
          "Клиентское API"
        ],
        "summary": "Получение доступных категорий услуг ПУ",
        "description": "Получение доступных категорий услуг ПУ",
        "operationId": "getCategories"
      }
    }
  },
  "components": {
    "securitySchemes": {
      "clientSecret": {
        "type": "apiKey",
        "name": "X-IBM-Client-Secret",
        "in": "header",
        "x-key-type": "client_secret"
      },
      "clientID": {
        "type": "apiKey",
        "name": "X-IBM-Client-Id",
        "in": "header"
      },
      "TPPOffersOAuth2Security": {
        "type": "oauth2",
        "description": "Сторонний поставщик использует поток авторизации сlient сredentional для доступа к ресурсам Поставщика услуг",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://bank.ru/oapi-channel/tokenUrl",
            "scopes": {
              "offers": "Доступ к информации о предложениях по продуктам"
            }
          }
        }
      },
      "PSUOffersOAuth2Security": {
        "type": "oauth2",
        "description": "Поток авторизации, требующий получения Сторонним поставщиком авторизации конечного Пользователя на доступ к ресурсам на сервере авторизации Поставщика услуг.",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://bank.ru/oapi-channel/authorize",
            "tokenUrl": "https://bank.ru/oapi-channel/token",
            "scopes": {
              "offers": "Доступ к информации о предложениях по продуктам"
            }
          }
        }
      },
      "TPPProductsOAuth2Security": {
        "type": "oauth2",
        "description": "Сторонний поставщик использует поток авторизации сlient сredentional для доступа к ресурсам Поставщика услуг",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://bank.ru/oapi-channel/tokenUrl",
            "scopes": {
              "products": "Доступ к информации об инициированных продуктах"
            }
          }
        }
      },
      "PSUProductsOAuth2Security": {
        "type": "oauth2",
        "description": "Поток авторизации, требующий получения Сторонним поставщиком авторизации конечного Пользователя на доступ к ресурсам на сервере авторизации Поставщика услуг.",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://bank.ru/oapi-channel/authorize",
            "tokenUrl": "https://bank.ru/oapi-channel/token",
            "scopes": {
              "products": "Доступ к информации об инициированных продуктах"
            }
          }
        }
      },
      "TPPOAuth2Security": {
        "type": "oauth2",
        "description": "Сторонний поставщик использует поток авторизации сlient сredentional для доступа к ресурсам Поставщика услуг",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://sb0.openbankingrussia.ru/sandbox0/as/aft/connect/token",
            "scopes": {
              "opendata": "Доступ к публичной информации"
            }
          }
        }
      },
      "EpaAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      },
      "TykApiKeyAuth": {
        "type": "apiKey",
        "in": "header",
        "name": "X-TYK-API-KEY"
      }
    }
  },
  "tags": [
    {
      "name": "Оплата баллами бонусов"
    }
  ]
}